[package]
name = "wfc"
version = "0.1.0"
authors = ["Michael Fairley <michaelfairley@gmail.com>"]
edition = "2018"

[dependencies]
rand = "*"

[dev-dependencies]
tobj = { path = "../../os/tobj" }
glium = "*"
cgmath = "*"
